actor_learning_rate: 0.0018
alpha_learning_rate: 0.0018
batch_size: 10000
buffer_size: 1000000
checkpoints_path: /home/catdog/workspace/drl-usv/offline/models/LB-SAC-custom
critic_layernorm: false
critic_learning_rate: 0.0018
device: cuda
edac_init: false
env_name: custom
eval_episodes: 5
eval_every: 5
gamma: 0.99
hidden_dim: 256
max_action: 1.0
name: LB-SAC-custom
normalize_reward: false
normalize_states: true
num_critics: 2
num_epochs: 500
num_updates_on_epoch: 1000
port: 11025
tau: 0.005
