alpha: 2.5
batch_size: 256
buffer_size: 1000000
checkpoints_path: /home/catdog/workspace/drl-usv/offline/models/TD3_BC-custom
device: cuda
discount: 0.99
env: custom
eval_freq: 5000
expl_noise: 0.1
load_model: ''
max_action: 1.0
max_timesteps: 500000
n_episodes: 5
name: TD3_BC-custom
noise_clip: 0.5
normalize_reward: false
normalize_states: true
policy_freq: 2
policy_noise: 0.2
port: 11024
tau: 0.005
