actor_dropout: null
actor_lr: 0.0003
batch_size: 256
beta: 3.0
buffer_size: 1000000
checkpoints_path: /home/catdog/workspace/drl-usv/offline/models/IQL-custom
device: cuda
discount: 0.99
env: custom
eval_freq: 5000
iql_deterministic: false
iql_tau: 0.7
load_model: ''
max_action: 1.0
max_timesteps: 500000
n_episodes: 5
name: IQL-custom
normalize_reward: false
normalize_states: true
port: 11035
qf_lr: 0.0003
tau: 0.005
vf_lr: 0.0003
