awac_lambda: 0.3333
batch_size: 256
buffer_size: 1000000
checkpoints_path: /home/catdog/workspace/drl-usv/offline/models/AWAC-custom
deterministic_torch: false
device: cuda
env_name: custom
eval_frequency: 5000
gamma: 0.99
hidden_dim: 256
learning_rate: 0.0003
max_action: 1.0
n_test_episodes: 5
name: AWAC-custom
normalize_reward: false
normalize_states: true
num_train_ops: 500000
port: 11023
tau: 0.005
