actor_learning_rate: 0.0003
alpha_learning_rate: 0.0003
batch_size: 256
buffer_size: 1000000
checkpoints_path: /home/catdog/workspace/drl-usv/offline/models/REM-custom
critic_learning_rate: 0.0003
deterministic_torch: false
device: cuda
env_name: custom
eval_episodes: 5
eval_every: 5
gamma: 0.99
hidden_dim: 256
max_action: 1.0
name: REM-custom
normalize_reward: false
normalize_states: true
num_critics: 50
num_epochs: 500
num_updates_on_epoch: 1000
port: 11033
tau: 0.005
